title: Morgan Fry # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome! I'm Morgan and I am passionate about utilizing data analytics to solve problems, from enterprise-level decision-making to process optimization. 
  I have earned a B.S. in Mathematics with a concentration in data science and also a Data Science Career Certificate. 
  I have professional experience developing BI dashboards, automated auditing systems, and ad hoc reports in the healthcare staffing industry. 
  I also have a background in QA and compliance.

  <br><br>
  <a href="https://www.linkedin.com/in/morgan-fry-a24706293/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
